### ISSUE TITLE
Test cases

### ISSUE THREAD

**Issue by mukeshm** [rammmukul/jsonParser#2]
Have more test cases with examples of where it should fail. Also move them to different directory.

**Comment by rammmukul** [comment]
Does this looks good?
https://github.com/rammmukul/jsonParser/tree/c0e774961ea19609c83a757a6f6a54dd271b9189

**Comment by mukeshm** [comment]
Have success and failure cases for all the value types in json. Also include complex structures and edge cases.

**Comment by rammmukul** [comment]
closed by https://github.com/rammmukul/jsonParser/commit/a39e697c761a9f31cb71b68d19960acbb17706dd
